# Generated by Django 3.0 on 2020-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.CharField(max_length=255)),
                ('key_column_name', models.CharField(default='key', max_length=32, verbose_name='Name of the key column')),
                ('key_regex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regex code for the key entries')),
                ('_db_key_column_name', models.CharField(blank=True, max_length=150, null=True)),
                ('_db_table_class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(editable=False)),
                ('_db_column_name', models.CharField(max_length=50, null=True)),
                ('column_type', models.CharField(choices=[('CH', 'Text field'), ('IN', 'Integer field'), ('FL', 'Float field')], default='CH', max_length=2)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_data_storage.DataTable')),
            ],
        ),
    ]
