# Generated by Django 3.0 on 2020-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_data_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='_db_column_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='column_type',
            field=models.CharField(choices=[('CH', 'Text field'), ('IN', 'Integer field'), ('FL', 'Float field')], default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='datatable',
            name='_db_key_column_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='_db_table_class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='key_column_name',
            field=models.CharField(default='key', max_length=32, verbose_name='Name of the key column'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='key_regex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regex code for the key entries'),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
