# Generated by Django 2.2.8 on 2021-01-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_data_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'permissions': (('migrate_datatable', 'User can migrate datatables'),)},
        ),
    ]
