# Generated by Django 3.0 on 2020-04-06 19:51
from django.utils.text import slugify
from django.db import migrations


def copy_data_from_DataStorage_module(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StoredDataCodeDeclaration = apps.get_model("DataStorage", "StoredDataCodeDeclaration")
    StoredDataDeclaration = apps.get_model("DataStorage", "StoredDataDeclaration")
    DataTable = apps.get_model("local_data_storage", "DataTable")
    DataColumn = apps.get_model("local_data_storage", "DataColumn")

    # for all pages, get all container. Copy all those containers and links
    for data_code_declaration in StoredDataCodeDeclaration.objects.all():
        data_table = DataTable(name=data_code_declaration.name,
                               slug=slugify(data_code_declaration.name),
                               description=data_code_declaration.description,
                               key_column_name=data_code_declaration.name,
                               key_regex=data_code_declaration.code_regex)
        data_table.save()

        for data_declaration in data_code_declaration.storeddatadeclaration_set.all():
            DataColumn(table=data_table,
                       slug=slugify(data_declaration.name),
                       name=data_declaration.name).save()


def copy_data_to_DataStorage_module(apps, schema_editor):

    pass


class Migration(migrations.Migration):

    dependencies = [
        ('local_data_storage', '0002_auto_20200405_1730'),
        ('DataStorage', '0003_auto_20190905_1657'),
    ]

    operations = [
        migrations.RunPython(copy_data_from_DataStorage_module, copy_data_to_DataStorage_module),
    ]
