# Generated by Django 2.1.5 on 2019-07-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDataCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoredDataCodeDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('code_regex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoredDataContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataStorage.StoredDataCode')),
            ],
        ),
        migrations.CreateModel(
            name='StoredDataDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('code_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataCodeDeclaration')),
            ],
        ),
        migrations.AddField(
            model_name='storeddatacontent',
            name='data_declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataDeclaration'),
        ),
        migrations.AddField(
            model_name='storeddatacode',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataCodeDeclaration'),
        ),
    ]
