# Generated by Django 2.2 on 2019-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0002_auto_20190905_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databatch',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
