# Generated by Django 3.0 on 2020-05-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCollective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Questionaire.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='InitiatedCollective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('inquirer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Inquirer')),
                ('tech_collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.TechCollective')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.SlugField(max_length=64, unique=True)),
                ('collective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiative_enabler.InitiatedCollective')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(blank=True, max_length=128, null=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.TechCollective')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Questionaire.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveDeniedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.InitiatedCollective')),
                ('inquirer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Inquirer')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveApprovalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1200)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.InitiatedCollective')),
                ('inquirer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Inquirer')),
            ],
        ),
    ]
