# Generated by Django 3.0 on 2020-05-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
        ('initiative_enabler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiversvp',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initiatedcollective',
            name='host_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='initiatedcollective',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='initiatedcollective',
            name='phone_number',
            field=models.CharField(default='n.a.', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techcollective',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Questionaire.Technology', unique=True),
        ),
    ]
