# Generated by Django 3.0 on 2020-05-12 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0004_auto_20200508_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiversvp',
            name='send_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
