# Generated by Django 3.0 on 2020-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0005_collectiversvp_send_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiatedcollective',
            name='message',
            field=models.TextField(default='Hey, ik heb een leuker idee. Laten we een collectief starten', max_length=500),
            preserve_default=False,
        ),
    ]
