# Generated by Django 3.0 on 2020-05-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
        ('initiative_enabler', '0006_initiatedcollective_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiversvp',
            name='activated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollectiveRSVPInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.InitiatedCollective')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer')),
            ],
        ),
    ]
