# Generated by Django 3.0 on 2020-05-13 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0007_auto_20200513_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiversvp',
            old_name='send_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='collectiversvp',
            name='last_send_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
