# Generated by Django 2.2.8 on 2020-05-21 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0009_auto_20200518_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiatedcollective',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
