# Generated by Django 2.2.8 on 2020-05-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
        ('initiative_enabler', '0010_initiatedcollective_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCollectiveInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interested', models.BooleanField(default=False)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer')),
                ('tech_collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_enabler.TechCollective')),
            ],
            options={
                'unique_together': {('tech_collective', 'inquirer')},
            },
        ),
    ]
