# Generated by Django 2.2.8 on 2020-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0012_auto_20200602_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcollectiveinterest',
            name='restriction_scopes',
            field=models.ManyToManyField(to='initiative_enabler.RestrictionValue'),
        ),
    ]
