# Generated by Django 2.2.8 on 2020-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0013_techcollectiveinterest_restriction_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiverestriction',
            name='public_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techcollective',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='initiative_enabler.CollectiveRestriction'),
        ),
        migrations.AlterField(
            model_name='techcollectiveinterest',
            name='restriction_scopes',
            field=models.ManyToManyField(blank=True, to='initiative_enabler.RestrictionValue'),
        ),
    ]
