# Generated by Django 2.2 on 2020-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0014_auto_20200609_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcollective',
            name='instructions_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
