# Generated by Django 2.2 on 2020-06-24 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
        ('initiative_enabler', '0015_techcollective_instructions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcollective',
            name='instructions_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.CreateModel(
            name='TechImprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_active', models.BooleanField(default=True)),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
        ),
    ]
