# Generated by Django 2.2.8 on 2020-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0018_auto_20200713_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcollective',
            name='restrictions',
            field=models.ManyToManyField(blank=True, through='initiative_enabler.RestrictionLink', to='initiative_enabler.CollectiveRestriction'),
        ),
    ]
