# Generated by Django 2.2.8 on 2020-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0019_techcollective_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictionrangeadjustment',
            name='type',
            field=models.CharField(default='NUM', max_length=3),
        ),
        migrations.AlterField(
            model_name='restrictionrangeadjustment',
            name='max',
            field=models.CharField(default=9999, max_length=24),
        ),
        migrations.AlterField(
            model_name='restrictionrangeadjustment',
            name='min',
            field=models.CharField(default=1000, max_length=24),
        ),
        migrations.AlterField(
            model_name='restrictionrangeadjustment',
            name='range',
            field=models.IntegerField(default=1, max_length=24),
        ),
    ]
