# Generated by Django 2.2.8 on 2020-07-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0020_auto_20200717_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionrangeadjustment',
            name='type',
            field=models.CharField(choices=[('NUM', 'Normal numeric number'), ('CMX', 'Complex value consisting of numbers and letters')], default='NUM', max_length=3),
        ),
    ]
