# Generated by Django 2.2.8 on 2020-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0021_auto_20200718_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionrangeadjustment',
            name='range',
            field=models.IntegerField(default=1),
        ),
    ]
