# Generated by Django 2.2.8 on 2021-05-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_is_static'),
        ('initiative_enabler', '0022_auto_20200720_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='techimprovement',
            name='instructions_file_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='techimprovement',
            name='instructions_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report'),
        ),
    ]
