# Generated by Django 2.2.8 on 2021-05-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_is_static'),
        ('initiative_enabler', '0023_auto_20210508_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techimprovement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='techcollective',
            name='instructions_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report'),
        ),
    ]
