# Generated by Django 2.2.8 on 2021-05-19 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0024_auto_20210509_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcollectiveinterest',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
