# Generated by Django 2.2.8 on 2021-05-19 12:58

from django.db import migrations


def set_creation_date(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TechCollectiveInterest = apps.get_model("initiative_enabler", "TechCollectiveInterest")
    db_alias = schema_editor.connection.alias
    for interest in TechCollectiveInterest.objects.using(db_alias).all():
        interest.last_updated = interest.inquirer.created_on
        interest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initiative_enabler', '0025_techcollectiveinterest_last_updated'),
    ]

    operations = [
        migrations.RunPython(set_creation_date),
    ]
