# Generated by Django 2.2.8 on 2021-06-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_data_storage', '0002_auto_20210126_1601'),
        ('initiative_enabler', '0027_auto_20210519_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionModifierBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionModifierRange',
            fields=[
                ('restrictionmodifierbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='initiative_enabler.RestrictionModifierBase')),
                ('min', models.CharField(default=1000, max_length=24)),
                ('range', models.IntegerField(default=1)),
                ('max', models.CharField(default=9999, max_length=24)),
                ('type', models.CharField(choices=[('NUM', 'Normal numeric number'), ('CMX', 'Complex value consisting of numbers and letters')], default='NUM', max_length=3)),
            ],
            bases=('initiative_enabler.restrictionmodifierbase',),
        ),
        migrations.AddField(
            model_name='restrictionlink',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiative_enabler.RestrictionModifierBase'),
        ),
        migrations.CreateModel(
            name='RestrictionModifierDataTable',
            fields=[
                ('restrictionmodifierbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='initiative_enabler.RestrictionModifierBase')),
                ('data_column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restriction_modifier_data_set', to='local_data_storage.DataColumn')),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_data_storage.DataTable')),
                ('text_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restriction_modifier_text_set', to='local_data_storage.DataColumn')),
            ],
            bases=('initiative_enabler.restrictionmodifierbase',),
        ),
    ]
