# Generated by Django 3.0 on 2020-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questionaire', '0001_initial'),
        ('PageDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.Page')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=('PageDisplay.page',),
        ),
        migrations.CreateModel(
            name='MailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField(default=False, verbose_name='Whether these mails are being send')),
                ('layout', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='PageDisplay.Page')),
            ],
        ),
        migrations.CreateModel(
            name='TimedMailTask',
            fields=[
                ('mailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionaire_mailing.MailTask')),
                ('days_after', models.IntegerField(default=7)),
                ('trigger', models.CharField(choices=[('TC', 'After completion'), ('TI', 'After creation (incomplete)'), ('LC', 'After Last Login (Completed)'), ('LI', 'After Last Login (Incomplete)')], max_length=2)),
            ],
            bases=('questionaire_mailing.mailtask',),
        ),
        migrations.CreateModel(
            name='ProcessedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_applicable', models.BooleanField(verbose_name='Whether the mail has been send')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquiry')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire_mailing.MailTask')),
            ],
            options={
                'unique_together': {('mail', 'inquiry')},
            },
        ),
    ]
