# Generated by Django 3.0 on 2020-04-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0002_auto_20200415_1511'),
        ('questionaire_mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredMailTask',
            fields=[
                ('mailtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionaire_mailing.MailTask')),
                ('event', models.CharField(choices=[(1, 'After mail registration'), (2, 'After inquiry completion')], max_length=3)),
            ],
            bases=('questionaire_mailing.mailtask',),
        ),
        migrations.AddField(
            model_name='processedmail',
            name='inquirer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer'),
        ),
        migrations.AlterField(
            model_name='processedmail',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquiry'),
        ),
    ]
