# Generated by Django 3.0 on 2020-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire_mailing', '0002_auto_20200323_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailpage',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
