# Generated by Django 3.0 on 2020-04-19 14:19

import PageDisplay.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0001_initial'),
        ('questionaire_mailing', '0002_auto_20200419_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquirerCodeModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
            ],
            bases=(PageDisplay.models.BasicModuleMixin, 'PageDisplay.basemodule'),
        ),
        migrations.AlterField(
            model_name='mailtask',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Tigger is active'),
        ),
        migrations.AlterField(
            model_name='triggeredmailtask',
            name='event',
            field=models.CharField(choices=[('MR', 'After mail registration'), ('IC', 'After inquiry completion')], max_length=3),
        ),
    ]
