# Generated by Django 2.2.8 on 2020-07-02 14:21

import PageDisplay.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0001_initial'),
        ('questionaire_mailing', '0003_auto_20200419_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfirmationLink',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
            ],
            bases=(PageDisplay.models.BasicModuleMixin, 'PageDisplay.basemodule'),
        ),
    ]
