# Generated by Django 2.2.8 on 2020-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire_mailing', '0004_mailconfirmationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeredmailtask',
            name='event',
            field=models.CharField(choices=[('MR', 'After mail registration in requiry'), ('MRN', 'After mail change in user-settings'), ('IC', 'After inquiry completion')], max_length=3),
        ),
    ]
