# Generated by Django 3.0 on 2020-04-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queued_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedtask',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queuedtask',
            name='progress',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='queuedtask',
            name='state',
            field=models.IntegerField(choices=[(2, 'Success'), (1, 'Processing'), (0, 'In queue'), (-1, 'Failed'), (-2, 'Cancelled')], default=0),
        ),
    ]
