# Generated by Django 3.0 on 2020-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queued_tasks', '0002_auto_20200412_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedcsvdataprocessingtask',
            name='deliminator',
            field=models.CharField(default=',', max_length=1),
        ),
    ]
