# Generated by Django 2.2.8 on 2020-06-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMailValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('activated', models.BooleanField(default=False)),
                ('activated_on', models.DateTimeField(blank=True, null=True)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer')),
            ],
        ),
    ]
