# Generated by Django 2.2.8 on 2020-06-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0004_inquirer_email_validated'),
        ('inquirer_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMailVerifyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer')),
            ],
        ),
        migrations.DeleteModel(
            name='PendingMailValidator',
        ),
    ]
