# Generated by Django 2.2.8 on 2020-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfilter',
            name='use_for_progress_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionfilter',
            name='use_for_tech_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
