# Generated by Django 3.0 on 2020-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questionaire', '0001_initial'),
        ('PageDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=128, unique=True)),
                ('file_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.Page')),
                ('description', models.TextField()),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('has_header_footer', models.BooleanField(default=True, verbose_name='Has a header or footer')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
            bases=('PageDisplay.page',),
        ),
        migrations.CreateModel(
            name='ReportDisplayOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('A3', 'A3 (297 x 420mm)'), ('A4', 'A4 (210 x 297mm)'), ('A5', 'A5 (148 x 210mm)')], default='A4', max_length=3)),
                ('orientation', models.BooleanField(choices=[(True, 'Standing'), (False, 'Rotated')], default=True)),
                ('margins', models.CharField(default='20mm 20mm 20mm 20mm', max_length=256)),
                ('header', models.CharField(blank=True, default='header', max_length=256, null=True)),
                ('footer', models.CharField(blank=True, default='footer', max_length=256, null=True)),
                ('report', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='display_options', to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='PageCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportPage')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyPageCriteria',
            fields=[
                ('pagecriteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.PageCriteria')),
                ('score', models.IntegerField(choices=[(1, 'Succesvol'), (2, 'Wisselend'), (0, 'Afgeraden'), (-1, 'Onbekend')])),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Technology')),
            ],
            bases=('reports.pagecriteria',),
        ),
        migrations.CreateModel(
            name='LogicPageCriteria',
            fields=[
                ('pagecriteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.PageCriteria')),
                ('logic', models.IntegerField(choices=[(0, 'OR'), (1, 'AND'), (2, 'NOR'), (3, 'NAND'), (4, 'XOR'), (5, 'XNOR')], default=0)),
                ('criteria', models.ManyToManyField(related_name='super_criteria', to='reports.PageCriteria')),
            ],
            bases=('reports.pagecriteria',),
        ),
    ]
