# Generated by Django 2.1.5 on 2019-11-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questionaire', '0031_answeroption_context_code'),
        ('PageDisplay', '0004_auto_20190907_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.Information')),
            ],
        ),
        migrations.CreateModel(
            name='PageCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, max_length=128, null=True)),
                ('file_name', models.CharField(max_length=128)),
                ('is_live', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogicPageCriteria',
            fields=[
                ('pagecriteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.PageCriteria')),
                ('logic', models.IntegerField(choices=[(0, 'OR'), (1, 'AND'), (2, 'NOR'), (3, 'NAND'), (4, 'XOR'), (5, 'XNOR')], default=0)),
            ],
            bases=('reports.pagecriteria',),
        ),
        migrations.CreateModel(
            name='TechnologyPageCriteria',
            fields=[
                ('pagecriteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.PageCriteria')),
                ('score', models.IntegerField(choices=[(1, 'Succesvol'), (2, 'Wisselend'), (0, 'Afgeraden'), (-1, 'Onbekend')])),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Technology')),
            ],
            bases=('reports.pagecriteria',),
        ),
        migrations.AddField(
            model_name='pagecriteria',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report'),
        ),
        migrations.AddField(
            model_name='logicpagecriteria',
            name='criteria',
            field=models.ManyToManyField(related_name='super_criteria', to='reports.PageCriteria'),
        ),
    ]
