# Generated by Django 2.1.5 on 2019-11-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='layout',
        ),
    ]
