# Generated by Django 3.0 on 2020-04-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='promotion_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text displayed near download option'),
        ),
    ]
