# Generated by Django 3.0 on 2020-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reports', '0002_remove_page_layout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='ReportPage',
        ),
    ]
