# Generated by Django 3.0 on 2020-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200203_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128),
        ),
    ]
