# Generated by Django 3.0 on 2020-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200203_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, unique=True),
        ),
    ]
