# Generated by Django 3.0 on 2020-02-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0011_imagemodule_mode'),
        ('reports', '0005_auto_20200203_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='A4_PageContainer',
            fields=[
                ('verticalmodulecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.VerticalModuleContainer')),
            ],
            bases=('PageDisplay.verticalmodulecontainer',),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='display_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.Page'),
        ),
    ]
