# Generated by Django 2.2.8 on 2020-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20201021_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='margins',
            field=models.CharField(default='20mm 20mm 20mm 20mm', max_length=64),
        ),
    ]
