# Generated by Django 2.2.8 on 2020-10-26 13:39

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_pagelayout_margins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpage',
            old_name='last_edited',
            new_name='last_edited_old',
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='template',
            field=models.FileField(blank=True, upload_to=reports.models.upload_layout_path),
        ),
        migrations.CreateModel(
            name='ReportPageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportPage')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
        ),
    ]
