# Generated by Django 2.2.8 on 2020-10-26 13:40

from django.db import migrations


def forwards_edit_date(apps, schema_editor):
    # Moves the last_edited from the ReportPage to the Page model (stored on a different db table)
    ReportPage = apps.get_model("reports", "ReportPage")
    db_alias = schema_editor.connection.alias
    for page in ReportPage.objects.using(db_alias).all():
        page.last_edited = page.last_edited_old
        page.save()


def reverse_edit_date(apps, schema_editor):
    # Moves the last_edited from the Page to the ReportPage model (stored on a different db table)
    ReportPage = apps.get_model("reports", "ReportPage")
    db_alias = schema_editor.connection.alias
    for page in ReportPage.objects.using(db_alias).all():
        page.last_edited_old = page.last_edited
        page.save()


def forward_report_page_links(apps, schema_editor):
    # Moves the last_edited from the ReportPage to the Page model (stored on a different db table)
    ReportPage = apps.get_model("reports", "ReportPage")
    ReportPageLink = apps.get_model("reports", "ReportPageLink")
    db_alias = schema_editor.connection.alias
    for page in ReportPage.objects.using(db_alias).all():
        ReportPageLink.objects.using(db_alias).create(
            report=page.report,
            page=page,
            page_number=page.page_number,
        )


def reverse_report_page_links(apps, schema_editor):
    # Moves the last_edited from the Page to the ReportPage model (stored on a different db table)
    ReportPageLink = apps.get_model("reports", "ReportPageLink")
    ReportPage = apps.get_model("reports", "ReportPage")
    db_alias = schema_editor.connection.alias
    for pagelink in ReportPageLink.objects.using(db_alias).all():
        page = pagelink.page
        page.page_number = pagelink.page_number
        page.report = pagelink.report
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20201026_1439'),
    ]

    operations = [
        migrations.RunPython(forwards_edit_date, reverse_edit_date),
        migrations.RunPython(forward_report_page_links, reverse_report_page_links),
    ]
