# Generated by Django 2.2.8 on 2020-10-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20201026_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPageMultiGenerated',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportpage',),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='multi_type',
            field=models.IntegerField(blank=True, choices=[(11, 'Advised techs'), (12, 'Not advised techs'), (13, 'No advise techs')], default=None, null=True),
        ),
    ]
