# Generated by Django 3.0 on 2020-02-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_reportpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpage',
            name='display_page',
        ),
    ]
