# Generated by Django 2.2.8 on 2020-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20201027_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPageSingle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportpage',),
        ),
        migrations.AddField(
            model_name='report',
            name='pages',
            field=models.ManyToManyField(through='reports.ReportPageLink', to='reports.ReportPage'),
        ),
    ]
