# Generated by Django 3.0 on 2020-02-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_reportpage_display_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecriteria',
            name='page',
        ),
    ]
