# Generated by Django 3.0 on 2020-02-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0011_imagemodule_mode'),
        ('reports', '0011_remove_pagecriteria_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpage',
            name='id',
        ),
        migrations.AddField(
            model_name='reportpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=52, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.Page'),
            preserve_default=False,
        ),
    ]
