# Generated by Django 2.2.8 on 2021-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20201113_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
