# Generated by Django 2.2.8 on 2021-04-03 19:40

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0011_auto_20210111_1219'),
        ('reports', '0012_report_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\I_Wou\\Documents\\Work\\Shakespeare\\reports/created_reports/'), upload_to='')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquiry')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
    ]
