# Generated by Django 3.0 on 2020-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_pagecriteria_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='has_header_footer',
            field=models.BooleanField(default=True, verbose_name='Has a header or footer'),
        ),
    ]
