# Generated by Django 3.0 on 2020-02-08 13:46

from django.db import migrations, models
import django.db.models.deletion


def create_report_display_options(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Report = apps.get_model("reports", "Report")
    ReportDisplayOptions = apps.get_model("reports", "ReportDisplayOptions")
    # For all reports, create the display options
    for report in Report.objects.all():
        ReportDisplayOptions.objects.create(
            report=report
        )


def destory_report_display_options(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    ReportDisplayOptions = apps.get_model("reports", "ReportDisplayOptions")
    ReportDisplayOptions.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_reportpage_has_header_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDisplayOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('A3', 'A3 (297 x 420mm)'), ('A4', 'A4 (210 x 297mm)'), ('A5', 'A5 (148 x 210mm)')], default='A4', max_length=3)),
                ('orientation', models.BooleanField(choices=[(True, 'Standing'), (False, 'Rotated')], default=True)),
                ('margins', models.CharField(default='20mm 20mm 20mm 20mm', max_length=256)),
                ('header', models.CharField(blank=True, default='header', max_length=256, null=True)),
                ('footer', models.CharField(blank=True, default='footer', max_length=256, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_options', to='reports.Report')),
            ],
        ),
        migrations.RunPython(create_report_display_options, destory_report_display_options),
    ]
