# Generated by Django 3.0 on 2020-02-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_reportdisplayoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdisplayoptions',
            name='report',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='display_options', to='reports.Report'),
        ),
    ]
