# Generated by Django 3.0 on 2020-02-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0012_whitespacemodule'),
        ('reports', '0016_auto_20200208_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContainer',
        ),
    ]
