# Generated by Django 3.0 on 2020-04-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PageDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, default='', help_text='De naam in de url, laat leeg om automatisch te genereren ut de titel', max_length=60, unique=True)),
                ('description', models.CharField(default='', max_length=128)),
                ('in_footer', models.BooleanField(default=True, verbose_name='Whether the page is linked in the footer')),
                ('footer_order', models.IntegerField(default=0, verbose_name='Order of appearance in the footer')),
                ('page', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='PageDisplay.Page')),
            ],
        ),
    ]
