# Generated by Django 3.0 on 2020-03-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepageurl',
            name='footer_order',
            field=models.IntegerField(default=0, verbose_name='Order of appearance in the footer'),
        ),
    ]
