# Generated by Django 3.0 on 2020-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_basepageurl_footer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepageurl',
            name='in_footer',
            field=models.BooleanField(default=True, verbose_name='Whether the page is linked in the footer'),
        ),
    ]
