# Generated by Django 2.1.5 on 2019-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
