# Generated by Django 3.0 on 2020-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techscoremodule',
            name='display_description',
            field=models.BooleanField(default=True, verbose_name='Display tech description'),
        ),
        migrations.AddField(
            model_name='techscoremodule',
            name='display_notes',
            field=models.BooleanField(default=True, verbose_name='Display scoring notes'),
        ),
        migrations.AddField(
            model_name='techscoremodule',
            name='display_sub_technologies',
            field=models.BooleanField(default=False, verbose_name='Display underlying technologies'),
        ),
    ]
