# Generated by Django 2.1.5 on 2019-05-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0002_auto_20190520_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerScoringNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='Nothing defined', null=True)),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.AnswerScoring')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
        ),
    ]
