# Generated by Django 2.1.5 on 2019-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0002_auto_20190311_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='validators',
            field=models.TextField(blank=True, null=True),
        ),
    ]
