# Generated by Django 3.0 on 2020-05-03 16:17

from django.db import migrations, models
import django.db.models.deletion


def set_default_values(apps, schema_editor):
    # Set the inquierer attributes. They were previously a property queried with inquiry.inquirer_set.first()
    Inquiry = apps.get_model('Questionaire', 'Inquiry')
    for inquiry in Inquiry.objects.all():
        inquiry.inquirer = inquiry.active_on_set.first()
        inquiry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0002_auto_20200415_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirer',
            name='active_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_set', to='Questionaire.Inquiry'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquirer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer'),
        ),
        migrations.RunPython(set_default_values),
        migrations.AlterField(
            model_name='inquiry',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquirer'),
        ),
    ]
