# Generated by Django 2.1.5 on 2019-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_question_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='validators',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
