# Generated by Django 2.1.5 on 2019-06-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_answerscoringnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerscoringnote',
            name='exclude_on',
            field=models.ManyToManyField(related_name='Answer_excludes', to='Questionaire.AnswerOption'),
        ),
        migrations.AddField(
            model_name='answerscoringnote',
            name='include_on',
            field=models.ManyToManyField(related_name='Answer_includes', to='Questionaire.AnswerOption'),
        ),
    ]
