# Generated by Django 2.2.8 on 2020-06-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20200503_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirer',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
