# Generated by Django 2.2 on 2020-07-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0001_initial'),
        ('Questionaire', '0004_inquirer_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PageDisplay.Page'),
        ),
    ]
