# Generated by Django 2.1.5 on 2019-06-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0004_auto_20190604_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscoringnote',
            name='exclude_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='Answer_excludes', to='Questionaire.AnswerOption'),
        ),
        migrations.AlterField(
            model_name='answerscoringnote',
            name='include_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='Answer_includes', to='Questionaire.AnswerOption'),
        ),
    ]
