# Generated by Django 2.1.5 on 2019-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0004_auto_20190312_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.SlugField(max_length=10),
        ),
    ]
