# Generated by Django 2.1.5 on 2019-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0005_auto_20190604_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringdeclaration',
            name='name',
            field=models.SlugField(max_length=32),
        ),
    ]
