# Generated by Django 2.1.5 on 2019-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0006_pageentry_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryquestionanswer',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
