# Generated by Django 2.1.5 on 2019-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0006_auto_20190604_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringdeclaration',
            name='slug',
            field=models.SlugField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerscoringnote',
            name='exclude_on',
            field=models.ManyToManyField(blank=True, related_name='Answer_excludes', to='Questionaire.AnswerOption'),
        ),
        migrations.AlterField(
            model_name='answerscoringnote',
            name='include_on',
            field=models.ManyToManyField(blank=True, related_name='Answer_includes', to='Questionaire.AnswerOption'),
        ),
        migrations.AlterField(
            model_name='scoringdeclaration',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
