# Generated by Django 2.2.8 on 2020-07-11 15:17

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TechGroup = apps.get_model("Questionaire", "TechGroup")
    db_alias = schema_editor.connection.alias
    TechGroup.objects.using(db_alias).update(
        display_in_step_1_list=True,
        display_in_step_2_list=True,
    )

    Technology = apps.get_model("Questionaire", "Technology")
    Technology.objects.using(db_alias).filter(
        techimprovement__is_active=True,
    ).update(
        display_in_step_3_list=True,
    )

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    TechGroup = apps.get_model("Questionaire", "TechGroup")
    db_alias = schema_editor.connection.alias
    TechGroup.objects.using(db_alias).update(
        display_in_step_1_list=False,
        display_in_step_2_list=False,
    )

    Technology = apps.get_model("Questionaire", "Technology")
    Technology.objects.using(db_alias).filter(
        techimprovement__is_active=True,
    ).update(
        display_in_step_3_list=False,
    )




class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0007_auto_20200711_1725'),
        ('initiative_enabler', '0017_auto_20200710_1543'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
