# Generated by Django 2.1.5 on 2019-04-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0007_inquiryquestionanswer_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerScoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_change', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_value', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('threshold_approve', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('threshold_deny', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Inquiry')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='answeroption',
            name='answer',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerscoring',
            name='answer_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.AnswerOption'),
        ),
        migrations.AddField(
            model_name='answerscoring',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology'),
        ),
    ]
