# Generated by Django 2.1.5 on 2019-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0008_auto_20190421_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerscoring',
            old_name='value_change',
            new_name='importance_change',
        ),
        migrations.RenameField(
            model_name='technologyscore',
            old_name='score',
            new_name='importance_score',
        ),
        migrations.AddField(
            model_name='answerscoring',
            name='usefulness_change',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologyscore',
            name='usefulness_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
