# Generated by Django 2.2 on 2019-06-16 12:31

from django.db import migrations, models
import django.db.models.deletion

def move_question_entry(apps, schema_editor):
    QuestionEntry = apps.get_model('Questionaire', 'PageEntry')
    QuestionEntryChild = apps.get_model('Questionaire', 'PageEntryQuestion')
    for qe in QuestionEntry.objects.all():
        qec = QuestionEntryChild(question_temp=qe.question, required_temp=qe.required)
        qec.page_entry = qe


def move_question_entry_back(apps, schema_editor):
    QuestionEntryChild = apps.get_model('Questionaire', 'PageEntryQuestion')
    for qec in QuestionEntryChild.objects.all():
        qe = qec.page_entry
        qe.question = qec.question_temp
        qe.required = qec.required_temp


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0008_auto_20190604_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEntryQuestion',
            fields=[
                ('pageentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Questionaire.PageEntry')),
                ('required_temp', models.BooleanField(default=False)),
                ('question_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Question')),
            ],
            bases=('Questionaire.pageentry',),
        ),
        migrations.CreateModel(
            name='PageEntryText',
            fields=[
                ('pageentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Questionaire.PageEntry')),
                ('text', models.TextField(default='')),
            ],
            bases=('Questionaire.pageentry',),
        ),
        migrations.AddField(
            model_name='pageentry',
            name='entry_type',
            field=models.PositiveIntegerField(choices=[(1, 'General information'), (2, 'Question')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='questions',
            field=models.ManyToManyField(through='Questionaire.PageEntryQuestion', to='Questionaire.Question'),
        ),
        migrations.RunPython(move_question_entry, move_question_entry_back),
    ]
