# Generated by Django 2.1.5 on 2019-04-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0009_auto_20190421_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
