# Generated by Django 2.2 on 2019-06-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0009_auto_20190616_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageentry',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pageentry',
            name='required',
        ),
    ]
