# Generated by Django 2.2 on 2019-06-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0010_auto_20190616_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageentryquestion',
            old_name='question_temp',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='pageentryquestion',
            old_name='required_temp',
            new_name='required',
        ),
    ]
