# Generated by Django 2.2.8 on 2021-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0010_inquirer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(choices=[(0, 'Open question'), (1, 'Integer question'), (2, 'Double question'), (3, 'Choice question'), (4, 'Yes-No question'), (5, 'Multiple choice question'), (6, 'Multiple YESNO question')]),
        ),
    ]
