# Generated by Django 2.1.5 on 2019-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0011_inquiryquestionanswer_processed_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='start_value',
            new_name='importance_start_value',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='threshold_approve',
            new_name='importance_threshold_approve',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='threshold_deny',
            new_name='importance_threshold_deny',
        ),
        migrations.AddField(
            model_name='technology',
            name='usefulness_start_value',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='technology',
            name='usefulness_threshold_approve',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='technology',
            name='usefulness_threshold_deny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
