# Generated by Django 2.2 on 2019-07-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0001_initial'),
        ('Questionaire', '0012_auto_20190724_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalQuestionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_source', models.CharField(max_length=256)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataDeclaration')),
                ('datacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataCodeDeclaration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Question')),
            ],
        ),
    ]
