# Generated by Django 2.2 on 2019-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0013_externalquestionsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalquestionsource',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Question'),
        ),
    ]
