# Generated by Django 2.2 on 2019-07-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0014_auto_20190725_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalquestionsource',
            old_name='datacode',
            new_name='datatype',
        ),
    ]
