# Generated by Django 2.1.3 on 2019-05-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0014_answervariable_storedvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comparison', models.PositiveIntegerField(choices=[(0, 'Higher'), (1, 'Higher or equal'), (2, 'Equal'), (3, 'Lower or Equal'), (4, 'Lower')])),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Page')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
        ),
    ]
