# Generated by Django 2.2 on 2019-07-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0015_auto_20190725_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalquestionsource',
            old_name='datatype',
            new_name='code_type',
        ),
    ]
