# Generated by Django 2.1.5 on 2019-05-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0015_pagerequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='current_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Questionaire.Page'),
        ),
    ]
