# Generated by Django 2.1.5 on 2019-05-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0016_inquiry_current_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comparison', models.PositiveIntegerField(choices=[(0, 'Higher'), (1, 'Higher or equal'), (2, 'Equal'), (3, 'Lower or Equal'), (4, 'Lower')])),
            ],
        ),
        migrations.CreateModel(
            name='StoredInquiryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='StoredValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=16)),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='answervariable',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pagerequirements',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagerequirements',
            name='technology',
        ),
        migrations.DeleteModel(
            name='StoredVariable',
        ),
        migrations.CreateModel(
            name='PageRequirementTechUsefulness',
            fields=[
                ('pagerequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Questionaire.PageRequirement')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
            bases=('Questionaire.pagerequirement',),
        ),
        migrations.DeleteModel(
            name='AnswerVariable',
        ),
        migrations.DeleteModel(
            name='PageRequirements',
        ),
        migrations.AddField(
            model_name='pagerequirement',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Page'),
        ),
    ]
