# Generated by Django 2.2 on 2019-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0016_auto_20190725_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='auto_process',
            field=models.BooleanField(default=False),
        ),
    ]
