# Generated by Django 2.1.5 on 2019-05-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0017_auto_20190506_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoredValue',
            new_name='StoredValueDeclaration',
        ),
    ]
