# Generated by Django 2.1.5 on 2019-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0017_page_auto_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
