# Generated by Django 2.2 on 2019-09-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0004_auto_20190907_1908'),
        ('Questionaire', '0019_question_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='information_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.Information'),
        ),
    ]
