# Generated by Django 2.1.5 on 2019-05-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0019_auto_20190506_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerScoringValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.AnswerOption')),
                ('stored_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.StoredValueDeclaration')),
            ],
        ),
    ]
