# Generated by Django 2.2 on 2019-09-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0020_technology_information_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='long_text',
        ),
    ]
