# Generated by Django 2.2 on 2019-09-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0022_auto_20190908_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
