# Generated by Django 2.1.5 on 2019-09-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0020_inquirer'),
        ('Questionaire', '0023_auto_20190909_0112'),
    ]

    operations = [
    ]
