# Generated by Django 2.1.5 on 2019-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0025_auto_20190926_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='exclude_on',
            field=models.ManyToManyField(related_name='exclude_questions', to='Questionaire.Question'),
        ),
        migrations.AddField(
            model_name='page',
            name='include_on',
            field=models.ManyToManyField(related_name='include_questions', to='Questionaire.Question'),
        ),
    ]
