# Generated by Django 2.1.5 on 2019-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0026_auto_20191007_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='exclude_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='exclude_questions', to='Questionaire.Question'),
        ),
        migrations.AlterField(
            model_name='page',
            name='include_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='include_questions', to='Questionaire.Question'),
        ),
    ]
