# Generated by Django 2.1.5 on 2019-10-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0028_auto_20191007_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechGroup',
            fields=[
                ('technology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Questionaire.Technology')),
                ('sub_technologies', models.ManyToManyField(blank=True, related_name='techgroups', to='Questionaire.Technology')),
            ],
            bases=('Questionaire.technology',),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
