# Generated by Django 2.1.5 on 2019-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0030_run_maketechgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='context_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
