# Generated by Django 2.1.5 on 2019-11-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0006_auto_20191106_1529'),
        ('Questionaire', '0031_answeroption_context_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechScoreModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaire.Technology')),
            ],
            bases=('PageDisplay.basemodule',),
        ),
    ]
