# Generated by Django 2.1.5 on 2019-11-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0032_techscoremodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='information_page',
        ),
    ]
