# Generated by Django 2.1.5 on 2019-11-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0034_technology_information_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='information_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.Page'),
        ),
    ]
