# Generated by Django 2.1.5 on 2019-11-25 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0035_auto_20191125_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
