# Generated by Django 3.0 on 2020-01-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0036_auto_20191125_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryquestionanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
