# Generated by Django 3.0 on 2020-02-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0037_auto_20200114_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(default='test_slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.SlugField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
