# Generated by Django 3.0 on 2020-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0038_auto_20200229_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
