# Generated by Django 3.0 on 2020-04-06 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0003_auto_20190905_1657'),
        ('local_data_storage', '0002_auto_20200405_1730'),
        ('Questionaire', '0039_inquiry_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalquestionsource',
            name='local_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_data_storage.DataColumn'),
        ),
        migrations.AddField(
            model_name='externalquestionsource',
            name='local_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_data_storage.DataTable'),
        ),
        migrations.AlterField(
            model_name='externalquestionsource',
            name='code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataCodeDeclaration'),
        ),
        migrations.AlterField(
            model_name='externalquestionsource',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataStorage.StoredDataDeclaration'),
        ),
    ]
