# Generated by Django 3.0 on 2020-03-30 15:01

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    BaseModule = apps.get_model("PageDisplay", "BaseModule")
    db_alias = schema_editor.connection.alias
    for module in BaseModule.objects.using(db_alias).filter(_type=11):
        module._type = 101
        module.save()


def reverse_func(apps, schema_editor):
    # Do not revert the effectr
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0039_inquiry_completed_on'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
