# Generated by Django 2.2 on 2019-09-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=999)),
                ('_type', models.PositiveIntegerField(choices=[(1, 'title_module'), (2, 'text_module'), (3, 'image_module')])),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.Information')),
            ],
        ),
    ]
