# Generated by Django 2.2 on 2019-09-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('PageDisplay.basemodule',),
        ),
        migrations.CreateModel(
            name='TextModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('text', models.TextField()),
            ],
            bases=('PageDisplay.basemodule',),
        ),
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('title', models.CharField(max_length=127)),
            ],
            bases=('PageDisplay.basemodule',),
        ),
    ]
