# Generated by Django 2.2 on 2019-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0002_imagemodule_textmodule_titlemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleModel',
            new_name='TitleModule',
        ),
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
