# Generated by Django 2.2.8 on 2020-07-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0002_downloadfilemodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containermodulepositionallink',
            options={},
        ),
    ]
