# Generated by Django 2.2 on 2019-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0003_auto_20190907_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemodule',
            name='size',
            field=models.PositiveIntegerField(default=1, help_text='The level of the title 1,2,3... maz 5'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='_type',
            field=models.PositiveIntegerField(choices=[(1, 'titlemodule'), (2, 'textmodule'), (3, 'imagemodule')]),
        ),
    ]
