# Generated by Django 2.2.8 on 2020-10-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0003_auto_20200710_1543'),
        ('reports', '0007_auto_20201026_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
