# Generated by Django 2.2.8 on 2021-01-16 16:02

import PageDisplay.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0004_page_last_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalURLModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('url', models.CharField(max_length=128, validators=[django.core.validators.URLValidator])),
                ('guide_text', models.CharField(default='View online', max_length=128)),
            ],
            bases=(PageDisplay.models.BasicModuleMixin, 'PageDisplay.basemodule'),
        ),
    ]
