# Generated by Django 2.1.5 on 2019-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0005_auto_20191106_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodule',
            name='_type',
            field=models.PositiveIntegerField(),
        ),
    ]
