# Generated by Django 2.2.8 on 2021-01-17 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0005_externalurlmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalurlmodule',
            name='url',
            field=models.CharField(max_length=128, validators=[django.core.validators.URLValidator()]),
        ),
    ]
