# Generated by Django 2.1.5 on 2019-11-19 15:18

from django.db import migrations, models
import django.db.models.deletion

def make_vert_pages(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Page = apps.get_model("PageDisplay", "Page")
    VerticalModuleContainer = apps.get_model("PageDisplay", "VerticalModuleContainer")
    ModuleContainer = apps.get_model("PageDisplay", "ModuleContainer")
    for container in ModuleContainer.objects.all():
        t = VerticalModuleContainer(modulecontainer_ptr=container)
        t.save()
        Page.objects.create(layout=t, name="-temp-name-")


def reverse_vert_pages(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_page_layout'),
        ('Questionaire', '0033_remove_technology_information_page'),
        ('PageDisplay', '0008_auto_20191115_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalModuleContainer',
            fields=[
                ('modulecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.ModuleContainer')),
            ],
            bases=('PageDisplay.modulecontainer',),
        ),
        migrations.RemoveField(
            model_name='information',
            name='modulecontainer_ptr',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.ModuleContainer'),
        ),
        migrations.RunPython(make_vert_pages, reverse_vert_pages),
    ]
