# Generated by Django 3.0 on 2019-12-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0009_auto_20191119_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.ModuleContainer'),
        ),
    ]
