# Generated by Django 3.0 on 2020-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0010_auto_20191218_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodule',
            name='mode',
            field=models.SlugField(choices=[('auto', 'Display full image'), ('full', 'Cover image')], default='auto'),
        ),
    ]
