# Generated by Django 3.0 on 2020-02-08 15:41

import PageDisplay.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0011_imagemodule_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteSpaceModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('height', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(limit_value=25), django.core.validators.MaxValueValidator(limit_value=1000)])),
            ],
            bases=(PageDisplay.models.BasicModuleMixin, 'PageDisplay.basemodule'),
        ),
    ]
