# Generated by Django 3.0 on 2020-03-30 15:49

import PageDisplay.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0012_whitespacemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerModulePositionalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=999)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='root_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PageDisplay.BaseModule'),
        ),
        migrations.CreateModel(
            name='OrderedContainerModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.BaseModule')),
                ('module_list', models.ManyToManyField(related_name='container', through='PageDisplay.ContainerModulePositionalLink', to='PageDisplay.BaseModule')),
            ],
            bases=(PageDisplay.models.ContainerModuleMixin, 'PageDisplay.basemodule'),
        ),
        migrations.CreateModel(
            name='VerticalContainerModule',
            fields=[
                ('orderedcontainermodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PageDisplay.OrderedContainerModule')),
            ],
            bases=('PageDisplay.orderedcontainermodule',),
        ),
        migrations.AddField(
            model_name='containermodulepositionallink',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_link', to='PageDisplay.OrderedContainerModule'),
        ),
        migrations.AddField(
            model_name='containermodulepositionallink',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_link', to='PageDisplay.BaseModule'),
        ),
    ]
