# Generated by Django 3.0 on 2020-03-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0013_auto_20200330_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodule',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PageDisplay.ModuleContainer'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=999, null=True),
        ),
    ]
