# Generated by Django 3.0 on 2020-04-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0015_auto_20200330_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containermodulepositionallink',
            options={'ordering': ['-position']},
        ),
    ]
