# Generated by Django 3.0 on 2020-04-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0016_auto_20200401_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodule',
            name='information',
        ),
        migrations.RemoveField(
            model_name='basemodule',
            name='position',
        ),
        migrations.RemoveField(
            model_name='page',
            name='layout',
        ),
        migrations.DeleteModel(
            name='ModuleContainer',
        ),
        migrations.DeleteModel(
            name='VerticalModuleContainer',
        ),
    ]
