# Generated by Django 3.0 on 2020-04-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageDisplay', '0017_auto_20200402_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='root_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PageDisplay.BaseModule'),
        ),
    ]
